install:
  - wget https://download.java.net/java/early_access/loom/7/openjdk-16-loom+7-285_linux-x64_bin.tar.gz
  - tar --extract --file openjdk-16-loom+7-285_linux-x64_bin.tar.gz -C ${HOME}
  - export JDK16=${HOME}/jdk-16
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source ./install-jdk.sh --feature 15
  - echo "JAVA_HOME=${JAVA_HOME}"
  - echo "JDK16=${JDK16}"
  - ./gradlew --version
  - ./gradlew publishToMavenLocal -x test -Porg.gradle.java.installations.fromEnv=JDK16 -Porg.gradle.java.installations.auto-download=false 
