name: Set up Test JDK
description: Sets up the JDK required to run platform-tooling-support-tests
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
    - uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net
        release: 21
    - shell: bash
      run: echo "JDK21=$JAVA_HOME" >> $GITHUB_ENV
